### ISSUE TITLE
"Title cannot be blank" error message appears on creating the new Release Log even though Title is specified

### ISSUE THREAD

**Issue by xeagle2** [iridakos/release_logs#23]
"Title cannot be blank" error message appears on creating the new Release Log even though Title not empty and properly specified.

Environment:
  Redmine version                3.0.3.stable
  Ruby version                   2.0.0-p645 (2015-04-13) [x64-mingw32]
  Rails version                  4.2.1
  Environment                    development
  Database adapter               Mysql2

  release_logs                   1.0.0

**Comment by xeagle2** [comment]
It shows in log: Unpermitted parameter: title

**Comment by xeagle2** [comment]
/plugins/release_logs/app/controllers/release_logs_controller.rb
there is a **" :title,"** missed at params.require, so the complete code should be like this below:

``` ruby
def release_log_params
    if Rails::VERSION::MAJOR >= 4
      params.require(:release_log).permit(
                                          :title,
                                          :description,
                                          :send_email_notification,
                                          :release_upon_publish,
                                          :release_date,
                                          :release_hour,
                                          :release_minutes,
                                          :attachments,
                                          :rollback_reason,
                                          :cancellation_reason,
                                          :release_log_entries_attributes => [
                                            :id,
                                            :issue_id,
                                            :release_log_entry_category_id,
                                            :include_in_notification,
                                            :note
                                          ])
    else
      params[:release_log]
    end
  end
```

**Comment by iridakos** [comment]
Will fix asap, thanks!

**Comment by chrismcdonald423** [comment]
Hey,
I'm getting a message"**Heads up:
title:  can't be blank**" while publishing my first article on https://dev.to/ website. Please resolve my query as soon as possible.
