### ISSUE TITLE
Can not "Rollback release" & "Cancel release"

### ISSUE THREAD

**Issue by hello2jack** [iridakos/release_logs#29]
Can not use "Rollback release" & "Cancel release".
![image](https://cloud.githubusercontent.com/assets/14246273/11992468/d98f107e-aa58-11e5-8265-35a2bd222bcb.png)

Environment:
Redmine version                3.0.5.stable
Ruby version                   1.9.3-p551 (2014-11-13) [x86_64-linux]
Rails version                  4.2.3
Environment                    production
Database adapter               Mysql2

**Comment by hello2jack** [comment]
Hi, i'm sorry, i didn't see the function in the bottom.
Sorry for disturb.
:)

![image](https://cloud.githubusercontent.com/assets/14246273/12033165/8fcd06c8-ae52-11e5-8015-abcd3b3341f9.png)

**Comment by iridakos** [comment]
@hello2jack Hi, no worries! I'm closing the issue.
